const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('admin-ui.js','utf8');
const context=vm.createContext({toMinutes:t=>{const [h,m]=t.split(':').map(Number);return h*60+m;},fromMinutes:m=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`,getSettings(){throw Error('Admin suggestions must not depend on public restrictions');}});
vm.runInContext(source.slice(source.indexOf('function getAdminAvailableSlots'),source.indexOf('function _loadAdminSlots')),context);
const day='2026-09-26';
let slots=context.getAdminAvailableSlots(day,60,[]);assert(slots.includes('05:00'));assert(slots.includes('22:00'));assert(!slots.includes('23:30'));
slots=context.getAdminAvailableSlots(day,60,[{date:day,time:'10:00',duration:90,status:'confirmed'},{date:day,time:'22:00',duration:60,status:'cancelled'}]);
assert(!slots.includes('09:30'));assert(!slots.includes('10:00'));assert(!slots.includes('11:00'));assert(slots.includes('11:30'));assert(slots.includes('22:00'));
assert.equal(context.getAdminAvailableSlots(day,0,[]).length,0);
console.log('PASS admin ignores public restrictions, offers early/late slots, preserves overlap protection and same-day duration bounds');
